export default {
  messages: [
    {
      role: "system",
      content:
        "You are a helpful assistant for a hospitality business called Manchester - Wilde, St. Peter's Square, and you are talking to a guest or potential guest of the business. Your sole job is to reliably invoke one or more of the provided tools so as to obtain accurate information to respond back to the guest with.\nCurrent date: Monday, 2025-01-06\n\n## Information Context\n### Business Information\nBusiness name: Manchester - Wilde, St. Peter's Square\nBusiness description: Inspired by the creativity and style of the brilliant Oscar Wilde, each apartment is a showroom for some of Ireland’s most talented independent artists, crafters and more, while the walls of communal areas are adorned with contemporary Irish photography sitting alongside locally inspired pieces.  Premium locations are of the essence to Wilde, as exemplified by our location on St. Peter’s Square, Manchester’s centre of business, history, arts and culture. Oxford Road train station with its direct trains to Manchester Airport, London, Liverpool and many other UK cities is just a 6 minute walk away. Chinatown, Manchester Art Gallery, Piccadilly Gardens, and the famous Arndale Shopping Centre are just some of the many top attractions on your doorstep here.\nBusiness locations: Manchester - Wilde, St. Peter's Square\n### Guest Room Number\nNot Provided\n\n## Instructions\n- You are EXPLICITLY FORBIDDEN from providing any answers to guest queries. The ONLY two scenarios when you may respond directly to the guest is to either 1. seek additional information such that a function can be properly invoked; 2.  directly acknowledge the guest when they thank you or say goodbye.\n- Refrain from answering with facts derived from your pre-training\n- For repeated guest queries or requests, do not mimic prior assistant responses from the conversation history to respond directly back to the guest. Again, treat each guest message as a new query requiring the use of one of the provided function tools.\n- Do not make assumptions about what values to plug into the function tools unless context from the conversation history are sufficient to infer what values to use. Ask for clarification if necessary.\n- You do not have live access to the business's property management system. Please ask the guest to contact the business directly for any requests that can't otherwise be handled by one of the provided tools.\n- Respond in the following style: sophisticated, artistic\n- If responding back to the guest directly please do so in the same language the guest used for their last message. If the last guest message contains words from different languages, use the PRIMARY language used. For example, if the guest uses the word 'Hallo' which implies German but the rest of the message is in English, respond in English.\n- I REPEAT, DO NOT UNDER ANY CIRCUMSTANCES PROVIDE DIRECT ANSWERS TO GUEST QUERIES. Remember your job is to invoke one or more of the provided tools.\n",
    },
    {
      role: "user",
      content:
        "Hi there, we are struggling to get the tv in our room to cast. Do you have any suggestions for how to make this work? Cheers!",
    },
    {
      role: "assistant",
      content:
        "Hi! I am an AI assistant for Wilde, St Peters Square and will do my best to help you with your queries. If you need to speak to a Frontdesk Agent, please let me know.\nI'm unsure of the specific steps for casting to the TV in your room. I recommend reaching out to our reception team for assistance. They will be delighted to help you with the setup.",
    },
    {
      role: "user",
      content: "Great. How do I speak to the reception team?",
    },
    {
      role: "assistant",
      content:
        "A staff member has been notified and will respond to your query as soon as they are able to. While you wait, you can continue to chat with me if you have any other questions or need further assistance.",
    },
    {
      role: "user",
      content: "Thank you",
    },
    {
      role: "assistant",
      content: "You're welcome!",
    },
    {
      role: "user",
      content: "How long will it take to hear back from a staff member?",
    },
    {
      role: "assistant",
      content:
        "Our reception is open 24 hours, so someone should be available to assist you promptly. If you haven't already, you can also try calling the reception directly from your room phone for immediate assistance.",
    },
    {
      role: "user",
      content: "Where is the room phone?",
    },
    {
      role: "assistant",
      content:
        "I'm unsure of the exact location of the room phone in your apartment. However, it is typically located on a bedside table or a desk. If you are unable to find it, please feel free to visit the reception on the 9th floor for assistance.\nHello, what is it saying after you press cast your device",
    },
    {
      role: "user",
      content:
        "Hi there. It goes onto the HDMI1 channel and then a small oval appears in the bottom left corner saying ‘no signal’",
    },
    {
      role: "assistant",
      content: "I can come up there in a moment if you wouldlike",
    },
    {
      role: "user",
      content: "I’d be grateful if someone could look at it tomorrow?",
    },
    {
      role: "assistant",
      content:
        "No problem, I can come up now to fix it if you would like or send maintenance in the morning",
    },
    {
      role: "user",
      content:
        "We’re going to bed now, can I message at a convenient time tomorrow morning?",
    },
    {
      role: "assistant",
      content:
        "Of course just let us know, do you have an approximate time as I can make a job note now",
    },
    {
      role: "user",
      content: "Great, thank you. Around 10am would be ideal.",
    },
    {
      role: "assistant",
      content: "No problem",
    },
    {
      role: "user",
      content:
        "Hi, would someone be able to come and look at the tv now please?",
    },
  ],
  tools: [
    {
      type: "function",
      function: {
        name: "questions_and_answers",
        description:
          "This is a general purpose questions and answers tool. This tool should nearly always be one of the tools chosen, unless an immediate response back to the guest is appropriate to request more information or to clarify the guest's intent. Check-in or early check-in requests should be handled by this tool.",
        parameters: {
          type: "object",
          properties: {
            vectordb_query: {
              type: "string",
              description:
                '\nConcise summaries of up to 3 distinct questions or statements that the guest is writing about.\nEach summary will be used as a stand-alone vector database query, so include all relevant context provided in the system prompt and from prior conversation history for optimal semantic retrieval.\nSummaries should be in the same language as the guest\'s latest message.\nSummaries should be separated by a ; (semicolon) character.\n\nExample:\nGuest: "What is the weather like in Toronto today? What should I wear?"\nProvider: "It is sunny in Toronto today. You can wear a t-shirt and shorts."\nGuest: "What about Vancouver?"\nVectorDB query: "What is the weather like in Vancouver today?;What should I wear in Vancouver today?"\n',
            },
            vectordb_query_without_locative_complement: {
              type: "string",
              description:
                "Modify the same exact vector db queries generated previously by removing the locative complement, which is the part of the sentence specifying a location. Maintain the grammatical structure and coherence of the queries after the removal.",
            },
          },
          required: [
            "vectordb_query",
            "vectordb_query_without_locative_complement",
          ],
        },
      },
    },
    {
      type: "function",
      function: {
        name: "rates_and_availabilities",
        description:
          "Tool used to query room or bed rates and availability for a hospitality property. It does NOT handle booking or reservation requests. Make sure to ask the guest to specify a guest count such that at least one of the guest count parameters is greater than 0.",
        parameters: {
          type: "object",
          properties: {
            start_date: {
              type: "string",
              description:
                "A guest's desired check-in date in YYYY-MM-DD date format. If possible try to infer this based on the guest's message; otherwise ask the guest to clarify.",
            },
            end_date: {
              type: "string",
              description:
                "A guest's desired check-out date in YYYY-MM-DD date format. If possible try to infer this based on the guest's message; otherwise ask the guest to clarify.",
            },
            adults: {
              type: "integer",
              description:
                "The number of adults in the guest's party. If the guest does not specify a number, use the default count of 0",
            },
            children: {
              type: "integer",
              description:
                "The number of children in the guest's party. If the guest does not specify a number, use the default count of 0",
            },
          },
          required: ["start_date", "end_date", "adults", "children"],
        },
      },
    },
    {
      type: "function",
      function: {
        name: "book_now",
        description:
          "Choose this tool when the guest has expressed the intent to make a booking or reservation.",
        parameters: {
          type: "object",
          properties: {
            intent: {
              type: "boolean",
              description:
                "Set to true if the guest's intent is to proceed to make a booking from a hospitality business",
            },
          },
          required: ["intent"],
        },
      },
    },
    {
      type: "function",
      function: {
        name: "connect_to_human",
        description:
          "\nChoose this tool when the guest has expressed any of the following intentions:\n- Connect to a human staff instead of continuing to chat with an AI bot.\n- Requesting booking modifications including but not limited to extending their stay, changing their room, cancellations, etc.\n- Requesting information on whether rooms are ready for their stay.\n- Requesting information about an existing housekeeping request or to update / cancel one.\n- Wanting to notify the staff about something.\n- Any other requests requiring a human staff to take action on.\n",
        parameters: {
          type: "object",
          properties: {
            intent: {
              type: "boolean",
              description:
                "Set to true if the guest's intent is to get connected to a human from the hospitality business instead of continuing to chat with the AI bot",
            },
          },
          required: ["intent"],
        },
      },
    },
    {
      type: "function",
      function: {
        name: "housekeeping",
        description:
          "Choose this tool when the guest is making a housekeeping or maintenance request. Make sure to call this tool ANY TIME the guest expresses a housekeeping request, even if it's repeated or similar to prior requests. DO NOT call this tool if the guest is seeking details about or make changes to a previously acknowledged housekeeping request (e.g. when items will be delivered/cleaned).",
        parameters: {
          type: "object",
          properties: {
            requests: {
              type: "array",
              description: "An array of requests that the guest just made.",
              items: {
                type: "object",
                properties: {
                  room: {
                    type: "string",
                    description:
                      "The guest's room where the housekeeping service is needed. If the guest room number is provided in the information context, use that. Do not assume that the room number is 'Room 901'. Ask the guest for their room number if unclear.",
                    enum: [
                      "Room 901",
                      "Room 902",
                      "Room 903",
                      "Room 904",
                      "Room 905",
                      "Room 906",
                      "Room 1001",
                      "Room 1002",
                      "Room 1003",
                      "Room 1004",
                      "Room 1005",
                      "Room 1006",
                      "Room 1007",
                      "Room 1008",
                      "Room 1009",
                      "Room 1010",
                      "Room 1011",
                      "Room 1012",
                      "Room 1013",
                      "Room 1014",
                      "Room 1015",
                      "Room 1016",
                      "Room 1017",
                      "Room 1018",
                      "Room 1019",
                      "Room 1020",
                      "Room 1021",
                      "Room 1022",
                      "Room 1023",
                      "Room 1101",
                      "Room 1102",
                      "Room 1103",
                      "Room 1104",
                      "Room 1105",
                      "Room 1106",
                      "Room 1107",
                      "Room 1108",
                      "Room 1109",
                      "Room 1110",
                      "Room 1111",
                      "Room 1112",
                      "Room 1113",
                      "Room 1114",
                      "Room 1115",
                      "Room 1116",
                      "Room 1117",
                      "Room 1118",
                      "Room 1119",
                      "Room 1120",
                      "Room 1121",
                      "Room 1122",
                      "Room 1123",
                      "Room 1201",
                      "Room 1202",
                      "Room 1203",
                      "Room 1204",
                      "Room 1205",
                      "Room 1206",
                      "Room 1207",
                      "Room 1208",
                      "Room 1209",
                      "Room 1210",
                      "Room 1211",
                      "Room 1212",
                      "Room 1213",
                      "Room 1214",
                      "Room 1215",
                      "Room 1216",
                      "Room 1217",
                      "Room 1218",
                      "Room 1219",
                      "Room 1220",
                      "Room 1221",
                      "Room 1222",
                      "Room 1223",
                      "Room 1301",
                      "Room 1302",
                      "Room 1303",
                      "Room 1304",
                      "Room 1305",
                      "Room 1306",
                      "Room 1307",
                      "Room 1308",
                      "Room 1309",
                      "Room 1310",
                      "Room 1311",
                      "Room 1312",
                      "Room 1313",
                      "Room 1314",
                      "Room 1315",
                      "Room 1316",
                      "Room 1317",
                      "Room 1318",
                      "Room 1319",
                      "Room 1320",
                      "Room 1321",
                      "Room 1322",
                      "Room 1323",
                      "Room 1401",
                      "Room 1402",
                      "Room 1403",
                      "Room 1404",
                      "Room 1405",
                      "Room 1406",
                      "Room 1407",
                      "Room 1408",
                      "Room 1409",
                      "Room 1410",
                      "Room 1411",
                      "Room 1412",
                      "Room 1413",
                      "Room 1414",
                      "Room 1415",
                      "Room 1416",
                      "Room 1417",
                      "Room 1418",
                      "Room 1419",
                      "Room 1420",
                      "Room 1421",
                      "Room 1422",
                      "Room 1423",
                      "Room 1501",
                      "Room 1502",
                      "Room 1503",
                      "Room 1504",
                      "Room 1505",
                      "Room 1506",
                      "Room 1507",
                      "Room 1508",
                      "Room 1509",
                      "Room 1510",
                      "Room 1511",
                      "Room 1512",
                      "Room 1513",
                      "Room 1514",
                      "Room 1515",
                      "Room 1516",
                      "Room 1517",
                      "Room 1518",
                      "Room 1519",
                      "Room 1520",
                      "Room 1521",
                      "Room 1522",
                      "Room 1523",
                      "Room 1601",
                      "Room 1602",
                      "Room 1603",
                      "Room 1604",
                      "Room 1605",
                      "Room 1606",
                      "Room 1607",
                      "Room 1608",
                      "Room 1609",
                      "Room 1610",
                      "Room 1611",
                      "Room 1612",
                      "Room 1613",
                      "Room 1614",
                      "Room 1615",
                      "Room 1616",
                      "Room 1617",
                      "Room 1618",
                      "Room 1619",
                      "Room 1620",
                      "Room 1621",
                      "Room 1622",
                      "Room 1623",
                      "Room 1701",
                      "Room 1702",
                      "Room 1703",
                      "Room 1704",
                      "Room 1705",
                      "Room 1706",
                      "Room 1707",
                      "Room 1708",
                      "Room 1709",
                      "Room 1710",
                      "Room 1711",
                      "Room 1712",
                      "Room 1713",
                      "Room 1714",
                      "Room 1715",
                      "Room 1716",
                      "Room 1717",
                      "Room 1718",
                      "Room 1719",
                      "Room 1720",
                      "Room 1721",
                      "Room 1722",
                      "Room 1723",
                      "Room 1801",
                      "Room 1802",
                      "Room 1803",
                      "Room 1804",
                      "Room 1805",
                      "Room 1806",
                      "Room 1807",
                      "Room 1808",
                      "Room 1809",
                      "Room 1810",
                      "Room 1811",
                      "Room 1812",
                      "Room 1813",
                      "Room 1814",
                      "Room 1815",
                      "Room 1816",
                      "Room 1817",
                      "Room 1818",
                      "Room 1819",
                      "Room 1820",
                      "Room 1821",
                      "Room 1822",
                      "Room 1823",
                      "Room 1901",
                      "Room 1902",
                      "Room 1903",
                      "Room 1904",
                      "Room 1905",
                      "Room 1906",
                      "Room 1907",
                      "Room 1908",
                      "Room 1909",
                      "Room 1910",
                      "Room 1911",
                      "Room 1912",
                      "Room 1913",
                      "Room 1914",
                      "Room 1915",
                      "Room 1916",
                      "Room 1917",
                      "Room 1918",
                      "Room 1919",
                      "Room 1920",
                      "Room 1921",
                      "Room 1922",
                      "Room 1923",
                      "Room 2001",
                      "Room 2002",
                      "Room 2003",
                      "Room 2004",
                      "Room 2005",
                      "Room 2006",
                      "Room 2007",
                      "Room 2008",
                      "Room 2009",
                      "Room 2010",
                      "Room 2011",
                      "Room 2012",
                      "Room 2013",
                      "Room 2014",
                      "Room 2015",
                      "Room 2016",
                      "Room 2017",
                      "Room 2018",
                      "Room 2019",
                      "Room 2020",
                    ],
                  },
                  job_item: {
                    type: "string",
                    description:
                      "The housekeeping job item that the guest is referring to. Be as accurate as possible in matching against valid options taking into account possible language translations. The item chosen MUST be exactly what the guest is referring to. If that is not possible then specify the item that the guest is referring to exactly and ignore the valid options list.",
                    enum: [
                      "1 dinner plate",
                      "1 small glass",
                      "2 blue pillows",
                      "2 cups",
                      "2 small duvets with covers",
                      "4 coasters",
                      "AHU 2",
                      "AHU Extract",
                      "Air Conditioning",
                      "Air Conditioning Filter",
                      "Air Conditioning - No Cooling",
                      "Air Conditioning - No Heat",
                      "Air Conditioning - Noisy",
                      "Air Conditioning - Not Working",
                      "Air Freshener",
                      "All lights not working",
                      "All pillows",
                      "Amenities Tray",
                      "Anniversary Card",
                      "Ansul System",
                      "Apartments",
                      "Artwork",
                      "Ash bin",
                      "ASHP",
                      "Ash Tray",
                      "baby cot",
                      "baby cot and high chair",
                      "Baby cot can’t close",
                      "Bar Cupboard Door",
                      "bar fridge",
                      "Bathmat",
                      "Bath - Not Draining",
                      "bathrobes",
                      "bathroom bin",
                      "Bathroom bin to change",
                      "Bathroom bin to fix",
                      "Bathroom bulb",
                      "bathroom ceiling",
                      "bathroom ceiling crack",
                      "bathroom door",
                      "bathroom drain",
                      "Bathroom edges",
                      "Bathroom glass door loose",
                      "bathroom glass shelf broke",
                      "Bathroom Light",
                      "Bathroom light flickering",
                      "Bathroom light not working",
                      "bathroom liking water",
                      "bathroom lock not working",
                      "bathroom mirror wire",
                      "Bathroom seepage on ceiling",
                      "bathroom shelf ",
                      "bathroom silicone ",
                      "bathroom sink",
                      "bathroom sink blocked",
                      "Bathroom Sink Overflow",
                      "bathroom sink stopper",
                      "bathroom sink tarnish",
                      "bathroom tap",
                      "bathroom tiles",
                      "Bath Rug",
                      "bathtoom liking water",
                      "Bath Towel",
                      "Bed",
                      "bed board to fix",
                      "Bed broken",
                      "bed cant move",
                      "bed drawer",
                      "bed Drawer Handle",
                      "bed drawer handle coming off",
                      "beddrom light panel not working",
                      "Bed Frame",
                      "Bed handle to fix",
                      "bed linen",
                      "bedroom blinds",
                      "bedroom bulb to fix",
                      "bedroom bulb wire to fix",
                      "bed room ceiling to paint",
                      "bedroom door",
                      "bedroom door chipped",
                      "bedroom door need paint touch up",
                      "Bedroom door not closing",
                      "bedroom door not opening",
                      "bedroom door scratched from inside",
                      "bedroom doors need painting",
                      "bedroom doors properly not opening good",
                      "bedroom door very hard to open",
                      "bedroom headoard ",
                      "Bedroom Light",
                      "bedroom lights loose",
                      "bedroom mirror cracked",
                      "Bedroom paint touch up",
                      "bedroom tv wall and kitchen wall need paint touch up",
                      "bedroom TV wall need painting",
                      "Bedroom wall light",
                      "bedroom wall needs paint touch up",
                      "Bed Runner",
                      "Bed Sheet - King",
                      "Bed Sheet - Single",
                      "bed shelf",
                      "bed shelf and fram broken",
                      "bed shelf door brok",
                      "bed side board missing",
                      "bed side lamp",
                      "bedside lamp",
                      "bedside light not working",
                      "Behind bathroom door",
                      "Behind maindoor",
                      "big casserole pot with lid ",
                      "big knife",
                      "Big Linen Skip",
                      "Big Plate",
                      "big pot",
                      "big spoons, small plate small bowl",
                      "bin area palltes to bin",
                      "Bin Bag - Bathroom Bin",
                      "Bin Bag - Kitchen Bin",
                      "bin frame broken",
                      "Binliner to put ",
                      "bin shelf door broken",
                      "Bin stickers missing",
                      "Birthday Card",
                      "black cushion",
                      "black cushions",
                      "black mark on the ceiling",
                      "Black water in toilet pots",
                      "Blanket",
                      "bleach",
                      "Blinds",
                      "Blinds Broken",
                      "Blind screw fix",
                      "blocked sink",
                      "Body Lotion",
                      "body shower holder ",
                      "Body Soap",
                      "Boiler 1",
                      "Boiler 2",
                      "book shelf ",
                      "Books (Wilde)",
                      "Bottled Water",
                      "bottle stand",
                      "bottom of the fridge",
                      "bottom part of the fridge ",
                      "Bread Knife",
                      "Breakfast Order Form",
                      "Brodericks Biscuits (Willde)",
                      "broken kitchen led light",
                      "broken toilet seat",
                      "bulb fuse",
                      "Bulb not working",
                      "buzzer",
                      "cabinet door",
                      "Call point cover",
                      "Can opener",
                      "cans",
                      "Card holder",
                      "Carpet Cleaner",
                      "Carpet - Torn",
                      "CCTV",
                      "Ceiling",
                      "ceiling crack ",
                      "Ceiling - Leak",
                      "Ceiling Light",
                      "ceiling seepage",
                      "ceiling silicone",
                      "ceramic stove",
                      "Cereal Bowl",
                      "Chair",
                      "change bathroom bin",
                      "change shower curtain",
                      "check door",
                      "Chewing Gum",
                      "chip on the bedroom ceiling",
                      "Chopping Board",
                      "chopping board and frying pan",
                      "cigarette bins ",
                      "Cladding",
                      "clean floor",
                      "Cleaning Chemicals",
                      "Cleaning Cloths",
                      "Cleaning Rags",
                      "clean room",
                      "clipboard for fire sign",
                      "Clip Frame",
                      "Closet Light",
                      "Clothing rail",
                      "Coaster (Wilde)",
                      "Coat Hook",
                      "coffee machine",
                      "Coffee Machine (Bar)",
                      "Coffee Maker",
                      "Coffee Mug",
                      "Coffee pod box missing",
                      "Coffee Pods - Decaf",
                      "Coffee Pods - Regular",
                      "Coffee Sachet",
                      "Coffee Set Up",
                      "coffee table",
                      "Coffee Table Books",
                      "Collect Rubbish",
                      "Comb",
                      "Comms Cabinet",
                      "Conditioner",
                      "control pad",
                      "cooker hood filter",
                      "Corkscrew",
                      "corridor door frame",
                      "Cot",
                      "Cot Sheets",
                      "Couch - Cushion",
                      "Crib",
                      "Crib Sheets",
                      "cupboard door",
                      "cupboard push to open broken",
                      "cups",
                      "curtain",
                      "Curtain for wash",
                      "curtain hook to fix",
                      "curtain needs wash",
                      "curtain pole",
                      "Curtains",
                      "Curtain stick missing",
                      "Curtain stick to fix",
                      "curtain to back",
                      "curtain to remove",
                      "curtain to wash",
                      "Cutlery",
                      "Cutlery - Dessert Spoon",
                      "Cutlery - Fork",
                      "Cutlery - Knife",
                      "Cutlery - Teaspoon",
                      "Daily In-house laundry cleaning",
                      "Damaged room floor",
                      "DDA Pull Cord",
                      "Deafgard",
                      "deliver 5 knife and 5 york",
                      "deliver curtain",
                      "delivery to move",
                      "dental kits",
                      "Deodorant - Female",
                      "Deodorant - Male",
                      "Desk",
                      "Desk Lamp",
                      "dinner plate",
                      "Dinner Spoon",
                      "dirty sofa bed",
                      "Dishes",
                      "dishwasher",
                      "Dishwasher broken",
                      "Dishwasher not working",
                      "Dishwasher Tablets",
                      "DND Light won't switch off",
                      "DND Sign",
                      "dnd sign won't off",
                      "Door",
                      "Door - Caulk",
                      "door chain",
                      "Door Closer",
                      "Door Frame",
                      "door frame to paint",
                      "door handle",
                      "Door handle broken",
                      "Door - Handle Broken",
                      "door handle brook",
                      "door is hard to open",
                      "door lock",
                      "Door - Lock",
                      "door locker need to fix",
                      "Door - Loose/not closing",
                      "Door - Noisy",
                      "door painting ",
                      "Door Release Break Glass",
                      "Door - Scratched",
                      "door slams",
                      "Door - Sliding Glass",
                      "doorstop",
                      "Door Stop",
                      "door threshold",
                      "dor locker brok",
                      "double duvet",
                      "Double duvet without zip",
                      "double protector ",
                      "Double Sheet and Duvet Cover",
                      "Double sofa bed cover",
                      "double throw",
                      "Draw",
                      "Drawer can’t open",
                      "drawer kitchen",
                      "Dresser",
                      "dryer",
                      "dryer not working",
                      "Dustpan & Brush",
                      "Duvet Cover - King",
                      "Duvet Cover - Single",
                      "Duvet - King",
                      "Duvet - Single",
                      "Elevator Doors",
                      "Elevator Light",
                      "Emergency Floor Plan",
                      "empty bin",
                      "empty linen trolley",
                      "Entry Light",
                      "Espresso Cup",
                      "Ethernet Cord",
                      "Evac Chair",
                      "excercise bike ",
                      "Exec Room - Bathrobe",
                      "Exec Room - Bathrobe & Slippers",
                      "Exec Room F&B Basket",
                      "Exec Room - Slippers",
                      "Extension Cord",
                      "extractor fan",
                      "Fan",
                      "Feminine Products",
                      "Fidge not working",
                      "Fire Alarm",
                      "Fire Alarm Panel",
                      "Fire blanket",
                      "Fire Detector Head",
                      "fire door",
                      "Fire Door Magnetic Door Locks",
                      "Fire Extinguisher",
                      "Fire hydrant red tag",
                      "Fire Notice",
                      "Fire notice board",
                      "Fire notice missing",
                      "Fire Panel",
                      "Fire Suppression",
                      "First Aid Kit",
                      "fix bedroom curtain",
                      "Fix cupboard area",
                      "fix  cupboard door",
                      "fix curtains",
                      "fix door locker",
                      "Fix floor lamp",
                      "fix kitchen bin door and toilet seat",
                      "fix kitchen shelf",
                      "Fix shower",
                      "fix small black table",
                      "fix the cable at the back of the TV",
                      "Fix the kitchen edge of the floor",
                      "fix the wall",
                      "fix toilet bin",
                      "fix toilet seat",
                      "fix wall",
                      "Fix wall next to main door",
                      "fix water in bathroom",
                      "Floor",
                      "floor 10 missing pillowcases and small hand towels",
                      "floor 15 all rooms dont have electricty",
                      "floor15 privatbroom missing pilowcasses",
                      "floor 15 privat room missing small hand towels",
                      "floor 19 , privat room needs a small towels and pillowcases",
                      "Floor - Carpet",
                      "Floor - Hardwood",
                      "Floor lamp fix",
                      "Floor - Marble",
                      "Floor - Pavement",
                      "Floor - Tile",
                      "Floor Walk - Entire Building",
                      "Floor - Wood",
                      "Food Waste Bin",
                      "freezer door",
                      "freezer door broke",
                      "freezer door cant open",
                      "freezer not work",
                      "Fridge",
                      "fridge doors not closed",
                      "fridge light not working",
                      "Fridge missing some parts",
                      "fridge not working",
                      "Fridge Shelf",
                      "frying pan",
                      "Gift Shop Item",
                      "Glass Bowl",
                      "Glasses",
                      "glass shelf",
                      "Glass shelf in the bathroom",
                      "glass shelve",
                      "glass tall",
                      "Grater",
                      "green cola",
                      "grey bag",
                      "grouting",
                      "guest toilet",
                      "guest toilet flush not working",
                      "Guest toilets to be scrubbed ",
                      "Gym Daily Check",
                      "Hair Dryer",
                      "Hairdryer Bag",
                      "Hallway Light",
                      "Hallway - Wall Damaged",
                      "Hand Dryer",
                      "Hand Soap",
                      "Hand Soap Bottle",
                      "Hand Towel",
                      "Hand Towel Dispenser",
                      "hand wash holder",
                      "handwash holder ",
                      "handwash to refill",
                      "handwassh",
                      "Hanger",
                      "Hanger - Clips",
                      "Hanger - Female",
                      "Hanger - Male",
                      "hanging light",
                      "Hatch",
                      "Headshower leakage",
                      "heater",
                      "Heat Lamp",
                      "high chair",
                      "hob broken",
                      "hole in the bedroom ceiling",
                      "Hole In Wall",
                      "hook",
                      "hooks",
                      "hooks for shower curtain",
                      "hook to take off",
                      "hoover",
                      "Hoover blocked",
                      "Hoover didn’t work floor 16",
                      "Hoover doesn’t work",
                      "hoover floor 14",
                      "hoover floor 15",
                      "hoover floor 17",
                      "Hoover not working",
                      "hub cap ",
                      "Humidifier",
                      "Ice Cube Tray",
                      "Ice Machine",
                      "In House Laundry",
                      "In House Laundry Filters",
                      "In Room Ipad",
                      "Insulation",
                      "ipad holder",
                      "Iron",
                      "iron and hair dryer",
                      "Iron Bag (Wilde)",
                      "Ironing Board",
                      "juice",
                      "kettle",
                      "key",
                      "key panel",
                      "Kids Plates & Cutlery",
                      "King duvet to deliver",
                      "king mattress ",
                      "Kitchen bin cabinet to fix",
                      "kitchen bin shelf door",
                      "kitchen board to fix",
                      "kitchen cabinet ",
                      "kitchen ceiling light not working",
                      "kitchen cover",
                      "Kitchen Cupboard Door",
                      "kitchen door and wall needs painting",
                      "kitchen door needs painting",
                      "Kitchen drawer to fix",
                      "kitchen exhaust fan cover",
                      "kitchen fire exhaust",
                      "Kitchen hob",
                      "kitchen induction",
                      "kitchen led",
                      "kitchen LED ",
                      "Kitchen LED Light",
                      "kitchen light",
                      "kitchen panel",
                      "kitchen shelf handle",
                      "kitchen shelf pop on to fix ",
                      "kitchen sink",
                      "kitchen sink blocked",
                      "kitchen sink drain cover",
                      "Kitchen Sink Overflow",
                      "kitchen sink overflow cover missing",
                      "Kitchen Sink Plug",
                      "Kitchen sink stopper",
                      "Kitchen sink stopper missing",
                      "kitchen skirting board to fix",
                      "Kitchen stopper",
                      "Kitchen stove",
                      "Kitchen table broken",
                      "kitchen tap is loose",
                      "kitchen wall",
                      "kitchen wall needs painting",
                      "kitchen walls needs painting",
                      "kitchen wall , tv wall and bedroom needs painting",
                      "Knife - Big",
                      "Knife - Small",
                      "kristilin",
                      "Ladder",
                      "Lamp",
                      "Lamp Diffuser",
                      "lamps are not on the same level",
                      "lamps not on the same level",
                      "Lamp very wobbly",
                      "Lap Top Cable",
                      "Late check Out",
                      "Laundry",
                      "Laundry Bag",
                      "Laundry Slip",
                      "leak",
                      "led bedroom",
                      "led kitchen light",
                      "led light kitchen",
                      "led livingroom",
                      "LED Window Strip",
                      "Legionella Checks",
                      "level lights",
                      "Lift Doors",
                      "Lift Lighting",
                      "lifts",
                      "Lift Screen",
                      "lift vda",
                      "light and control panel",
                      "light bulb",
                      "light control pad",
                      "Light Diffuser",
                      "light flickering",
                      "Lighting",
                      "Light is dim",
                      "Light near window",
                      "light next to the Tv not working",
                      "light panel",
                      "lights not working",
                      "light stripped",
                      "Light Switch",
                      "light tripped",
                      "Linen Delivery",
                      "Linen - Strip Room",
                      "linen Trolley",
                      "Lint Roller",
                      "liquid tube",
                      "living room door to paint",
                      "living room lamp not working",
                      "living room mirror demage",
                      "living room needs to be painted",
                      "Living room paint touch up",
                      "living room rug to pull ",
                      "living room to paint",
                      "living room tv wall needs painting",
                      "Living room TV Wall needs painting urgently",
                      "Lost Property Item",
                      "Lotion",
                      "Lounge Wall",
                      "Luggage",
                      "Luggage Rack",
                      "maindoor",
                      "maindoor chain hole to refill",
                      "Main door handle loose",
                      "maindoor hard to close",
                      "maindoor hard to open",
                      "maindoor lock",
                      "Maindoor not open",
                      "Main door not opening",
                      "Main door rubber seal",
                      "maindoor to paint",
                      "main door won’t close",
                      "make bed as twin",
                      "make double",
                      "Make Up Mirror",
                      "Makeup Remover Wipes",
                      "Marble - Cracked",
                      "marks on the table",
                      "marks on the wall",
                      "Masher",
                      "master key",
                      "Mastic",
                      "Matches",
                      "Mattress",
                      "Mattress Protector",
                      "mattress protector and linen ",
                      "mattress to change",
                      "Measuring Jug",
                      "Menu (Wilde)",
                      "meter reads",
                      "Microwave",
                      "microwave glass plate",
                      "Microwave Light Film",
                      "Microwave not working",
                      "Milk",
                      "Mini Fridge",
                      "Mirror",
                      "Mirror - Cracked",
                      "mirror drawer",
                      "mirror light ",
                      "mirror light and Kitchen LED light",
                      "Mirror missed screws",
                      "mirror missing",
                      "Mirror Screw Cap",
                      "mirror shelf",
                      "Missed floor stand lamp",
                      "missing dishwasher off/on button",
                      "Mop",
                      "Mouldex Shower",
                      "Mouthwash",
                      "Move couch",
                      "Mug",
                      "nails sticking out - bed",
                      "Near toilet seat wall need grouting",
                      "need fix door locker",
                      "needs a chinge cimicaly in laundry soon and possible",
                      "needs painting ceiling",
                      "Nespresso Coffee Machine",
                      "net curtains",
                      "Newspaper",
                      "Night Light",
                      "no electricity",
                      "Noise",
                      "No light in fridge",
                      "No lights",
                      "number plague ",
                      "one hook missing",
                      "Other",
                      "oven",
                      "Oven Glove",
                      "Ozone Machine",
                      "pain",
                      "pain door frame",
                      "paint",
                      "Paint 1 wall bed wall",
                      "Paint ceiling",
                      "paint door",
                      "Paint full apartment inc skirting boars",
                      "painting",
                      "painting behind main door ",
                      "painting door",
                      "Paint roof",
                      "paint room",
                      "paint skirting board",
                      "paint the two black small tables",
                      "paint wall",
                      "Paint wall asap please",
                      "Paint walls",
                      "Paper",
                      "Paper Hand Towels",
                      "parcel",
                      "Peloton Bike",
                      "Pen",
                      "Pencil",
                      "Pencil (Wilde)",
                      "Pepper",
                      "Phone Charger",
                      "picture framebroken",
                      "pillow",
                      "Pillowcase",
                      "pillow cases",
                      "Pillowcases.",
                      "pillowcases and king sheets",
                      "Pillow - Feather",
                      "Pillow - Foam",
                      "pillows",
                      "Pipe noise",
                      "Pizza Cutter (Wilde)",
                      "Plant",
                      "plates",
                      "please check kitchen staff freeg",
                      "please clean ground floor bin area",
                      "please fix the rug",
                      "please fix towel holder",
                      "plug socket",
                      "Plug sockets not working",
                      "Pool Towel",
                      "poor ventilation in the room,mold is forming behind the sofa bed",
                      "Postcard (Wilde)",
                      "Poster Frame",
                      "Posters",
                      "Private Room",
                      "private room door lock",
                      "puffer",
                      "Pull out drawer",
                      "Push button",
                      "push the sofa  back on the place",
                      "put back the rug",
                      "put the shelves back on the wall",
                      "Put up curtain",
                      "put up net curtain",
                      "put up net curtain in 1501",
                      "put up net curtains",
                      "Put up shelves",
                      "Q Tips",
                      "Razor",
                      "Reception Doors",
                      "Reception Tables",
                      "Recycle/Waste Stickers",
                      "Recycling Stickers",
                      "reffill the oasis pro purple liquidin laundry asap please",
                      "refresh living room walls",
                      "refresh room walls",
                      "refuge Alarm",
                      "rehook curtain",
                      "re hook net curtain",
                      "rehook net curtain",
                      "rehook shower",
                      "re hook shower curtain",
                      "Remote Batteries",
                      "Remote Control",
                      "Remove cot",
                      "Remove Paint",
                      "Remove paint off the wall paper",
                      "repair kitchen sink",
                      "repair light panel",
                      "repair shower dryn",
                      "repair step",
                      "Repair tv",
                      "replace bathroom sink",
                      "replace electrik panel",
                      "replace kitchen sink",
                      "replace lamp with bed",
                      "Restock towels",
                      "Riser Cupboard",
                      "Riskproof",
                      "Robe",
                      "Rollaway Bed",
                      "room clean ",
                      "room dont have water",
                      "room doors not closing properly good",
                      "room doors not opening",
                      "room doors stay opening all time",
                      "room dors not closing",
                      "room electric panel",
                      "room needs painting",
                      "Room Service Menu",
                      "Room Service Table",
                      "Room Service Tray",
                      "room smell",
                      "Rotate Mattress",
                      "Rug",
                      "Safe",
                      "Safe Sticker",
                      "safety chain",
                      "safety chain hole",
                      "Safe - Will not open",
                      "Safe - Will not shut",
                      "Salt",
                      "Salt & Pepper (Wilde)",
                      "sauce pans",
                      "scrach on the door",
                      "Screen",
                      "seal on the shower door",
                      "seat vinyl",
                      "Serving Spoon",
                      "Sewing Kit",
                      "Shampoo",
                      "shampoo bottle to change",
                      "shampoo holder",
                      "Shaver Socket",
                      "Shelf",
                      "Shower",
                      "shower area light blinking",
                      "Shower bar",
                      "shower basin",
                      "Shower Cap",
                      "shower ceiling",
                      "shower cubicle paint peeling off",
                      "Shower - Curtain Rod",
                      "Shower door.",
                      "Shower door lock broken",
                      "shower door won’t close",
                      "Shower Drain",
                      "Shower drain blockage",
                      "shower drain cover missing",
                      "shower dripping",
                      "Shower Gel",
                      "Shower - Glass Door",
                      "Shower - Grab Bar",
                      "Shower - Grout",
                      "shower handle",
                      "Shower - Handle",
                      "shower head",
                      "Showerhead",
                      "Shower head came off",
                      "shower head holder broken ",
                      "shower holder broken",
                      "shower holder handle to fix",
                      "shower hose",
                      "shower hub missing",
                      "shower knob",
                      "shower leakage",
                      "shower leaking",
                      "Shower - Leaking",
                      "Shower - No Cold Water",
                      "Shower - No Hot Water",
                      "shower not working",
                      "shower pole off the ",
                      "shower running",
                      "shower screen",
                      "Shower Seal",
                      "Shower - Switch",
                      "Shower tap",
                      "shower tap cover missing",
                      "Shower threshold",
                      "Shower - Tile",
                      "shower tray",
                      "shower won't switch off",
                      "showe tap",
                      "Side of sofa",
                      "Signs in the lift to be wiped",
                      "silicone in shower",
                      "silicone in shower on the ceiling",
                      "Silverware",
                      "single duvet and duvet cover",
                      "single sofa bed protector",
                      "Sink",
                      "sink blocked",
                      "Sink - Caulking",
                      "Sink - Faucet",
                      "sink leakage",
                      "sink lid",
                      "Sink - Not Draining",
                      "Sink - Sealant",
                      "skirting board need to be painted",
                      "skirting board repair",
                      "Skirting Boards",
                      "skirting board to fix near bed",
                      "Slippers",
                      "Slotted Spoon",
                      "Small Book",
                      "small cooking pot ",
                      "small glass",
                      "small glass and wine glass ",
                      "small glasses",
                      "Small Plate",
                      "Small pot",
                      "small spoons",
                      "smell",
                      "Smell Machine",
                      "smoke",
                      "smoke dectector blinking",
                      "Soap Dish",
                      "soap dish loose",
                      "sockets not working",
                      "Sofa",
                      "Sofa Bed",
                      "sofa bed broken",
                      "sofa bed mattress",
                      "Sofa Bed Pack",
                      "Sofa bed to move",
                      "Sofa - Cushion",
                      "Sofa protector",
                      "Split Bed to Twin",
                      "spy hole loose",
                      "Squeaky bed",
                      "staff toilet block",
                      "Staircase door on floor 9 to be wiped and scrubbed ",
                      "Standing lamp plug to change",
                      "Standing lamp to replace",
                      "stayover",
                      "sticker on ash bin outside main door to be removed ",
                      "Strainer",
                      "sugar",
                      "switch plate",
                      "table",
                      "Table bubbling",
                      "Table chipped",
                      "table top",
                      "take down bedroom curtain",
                      "Take down living room curtain",
                      "Take down net curtains",
                      "take down the net curtains",
                      "take out the broken mirror from the room",
                      "tall glass",
                      "tall water glass",
                      "tap broken",
                      "tap leaking",
                      "Tea Bags",
                      "Teabags - Green Tea (Wilde)",
                      "tea cup, water glass",
                      "Tea Towel",
                      "Telephone",
                      "test",
                      "the electrical cables are on the upper shelf in the bedroom",
                      "the refrigerator does not work",
                      "Thermostat",
                      "Throw",
                      "Tidy cable at the back of the TV",
                      "Tidy tv cable",
                      "Tissue Box",
                      "Tissues",
                      "Toaster",
                      "Toilet",
                      "Toilet - Base Broken",
                      "toilet block",
                      "toilet blocked",
                      "toilet brush and holder",
                      "toilet brush holder to fix",
                      "toilet button",
                      "Toilet - Clogged",
                      "toilet flush ",
                      "Toilet flush",
                      "Toilet flush not working",
                      "Toilet - Handle Broken",
                      "toilet lights",
                      "Toilet - Not Flushing",
                      "Toilet Paper",
                      "toilet roll holder",
                      "Toilet rolls",
                      "toilet seat",
                      "toilet seat loose",
                      "Toilet - Seat Loose",
                      "Toilet sink blocked",
                      "Toothbrush",
                      "Toothpaste",
                      "toster ",
                      "towel",
                      "Towel hanger not heating",
                      "towel rail",
                      "towels",
                      "Trash",
                      "Trash Can Liner",
                      "Travel Adapter",
                      "Travel Kit",
                      "Triple Bracket",
                      "Tub",
                      "Tub - Not Draining",
                      "TV",
                      "Tv and kitchen wall needs painting",
                      "tv broken",
                      "TV cable is damaged",
                      "TV - Chromecast",
                      "TV - No Picture",
                      "TV - No Sound",
                      "tv remote",
                      "tv signal proble",
                      "tv stand",
                      "Tv to fix",
                      "TV wall needs painting",
                      "TV Wall needs paint touch up",
                      "TV wall need to be painted",
                      "TV walls needs to be painted",
                      "TV - Will not Turn Off",
                      "TV - Will not Turn On",
                      "Tv wires",
                      "twin",
                      "Two tall glasses",
                      "Umbrella (Wilde)",
                      "Unblock sink",
                      "USB Socket",
                      "Vacuum",
                      "Vacuum Cleaner",
                      "vain glass",
                      "Vanity",
                      "Vanity - Cracked",
                      "Vanity Kit",
                      "VDA Panel (Wilde)",
                      "very hard opening room dors",
                      "vine gla",
                      "VIP Pack",
                      "wall",
                      "Wall crack near maindoor",
                      "Wall hanger broken",
                      "wall lamp broken",
                      "wall light - bulb missing",
                      "Wall light isnt working",
                      "wall light not working in the sitting room",
                      "wall needs painting",
                      "wall needs paint touch up",
                      "Wall paint chipped",
                      "Wall painting requires",
                      "Wallpaper",
                      "wall seepage",
                      "walls need painting",
                      "walls need paint touch up",
                      "Washcloth",
                      "Washing Machine",
                      "Washing Up Liquid",
                      "Water Glass",
                      "water glass wine glass",
                      "Water Noise",
                      "Water Pressure",
                      "Water (Wilde)",
                      "Weekly Flushing",
                      "Weird noise from maindoor",
                      "Welcome Card",
                      "Window",
                      "window area light broken",
                      "window area sticker",
                      "Window blinds",
                      "Window - Curtain",
                      "Window - Curtain Broken",
                      "wine glass",
                      "Wine Glass",
                      "wine glasses",
                      "Wood Breakfast Tables",
                      "wooden hanger torn off",
                      "Wooden Pallet - Dispose",
                      "Wooden Panel",
                      "wooden scan cubes",
                      "zip in bed ",
                    ],
                  },
                  action: {
                    type: "string",
                    description: "The action that the guest wants to perform",
                    enum: [
                      "deliver",
                      "inspect",
                      "clean",
                      "repair",
                      "remove",
                      "replace",
                      "install",
                      "perform",
                    ],
                  },
                  quantity: {
                    type: "integer",
                    description:
                      "Where it makes sense and if the guest specifies, the quantity of the action that the guest wants to perform. Default to 1",
                  },
                  request_summary: {
                    type: "string",
                    description:
                      "A short sentence summary of the guest request, in the English language.",
                  },
                },
                required: [
                  "room",
                  "job_item",
                  "action",
                  "quantity",
                  "request_summary",
                ],
              },
            },
          },
          required: ["requests"],
        },
      },
    },
  ],
};
